// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI3AQPfFLXHB2PkFJW9xzBytdrJy2esy4',
    appId: '1:90817750920:web:df0ce3a368899789dd7c3d',
    messagingSenderId: '90817750920',
    projectId: 'tripify-first',
    authDomain: 'tripify-first.firebaseapp.com',
    storageBucket: 'tripify-first.appspot.com',
    measurementId: 'G-CKN3ZW9PFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbxyC0jLcgrjQODKyb49ryMFuWjZ193eE',
    appId: '1:90817750920:android:8291ade3eceaef19dd7c3d',
    messagingSenderId: '90817750920',
    projectId: 'tripify-first',
    storageBucket: 'tripify-first.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvRKU3On_YiZ7b4t3VGJq4zgbXZ2Uxa8A',
    appId: '1:90817750920:ios:37a397a09ebef728dd7c3d',
    messagingSenderId: '90817750920',
    projectId: 'tripify-first',
    storageBucket: 'tripify-first.appspot.com',
    iosClientId: '90817750920-9307of40hl4eg62dabtvcd403s6pg5a8.apps.googleusercontent.com',
    iosBundleId: 'com.tripify.tripify-first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvRKU3On_YiZ7b4t3VGJq4zgbXZ2Uxa8A',
    appId: '1:90817750920:ios:1788051e38bbedb1dd7c3d',
    messagingSenderId: '90817750920',
    projectId: 'tripify-first',
    storageBucket: 'tripify-first.appspot.com',
    iosClientId: '90817750920-fjnc0lhbluq45fkm8g3igutfqjosh3kk.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
